# Generated by Django 4.2.7 on 2025-10-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user')], max_length=120, unique=True, verbose_name='Название роли'),
        ),
    ]
